net.p2p: add p2p package written by liyang.
Package p2p uses https://libp2p.io libraries, which is used in https://ipfs.io.
But the libp2p go packages seems have some issues.

When I execute `make test`, it throws the following error:
vendor/github.com/ipfs/go-ipfs-util/util.go:20:25: undefined: multihash.SHA2_256
vendor/github.com/ipfs/go-ipfs-util/util.go:131:12: undefined: multihash.Sum
vendor/github.com/whyrusleeping/mafmt/patterns.go:19:25: undefined: multiaddr.P_UTP
vendor/github.com/whyrusleeping/mafmt/patterns.go:22:26: undefined: multiaddr.P_QUIC
vendor/github.com/whyrusleeping/mafmt/patterns.go:31:31: undefined: multiaddr.P_IPFS
vendor/github.com/whyrusleeping/mafmt/patterns.go:64:30: too many arguments in call to ptrn.partialMatch

It seems like those packages have dependencies issues: package didn't catch up to the depdency's code change.